name: UPDATE PROFIL

on:
  push:
    branches:
      - master
    paths:
      - "assets/new.png"
  workflow_dispatch:
    inputs:
      my_input:
        description: 'update profile'
        required: true
jobs:
  build_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: node ./bin/updateProfile.mjs
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[CI] update readme and assets"
          git push
